//! Synthetic MDP 3.0 stream generator.
//!
//! Each instrument's mid follows a discrete Ornstein-Uhlenbeck (mean-reverting)
//! process so the connector's z-score signal genuinely crosses its thresholds.
//! Packets are built with the production [`crate::mdp3::encode`] path, so the
//! generated bytes are decoded identically to real CME data. A fixed seed makes
//! the whole stream reproducible.

use crate::mdp3::book_refresh::MdEntry;
use crate::mdp3::encode::PacketBuilder;
use crate::mdp3::enums::{MdEntryType, MdUpdateAction};
use crate::{f64_to_price9, InstrumentId};

/// Deterministic SplitMix64 PRNG with a standard-normal sampler.
#[derive(Debug, Clone)]
struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    fn new(seed: u64) -> SplitMix64 {
        SplitMix64 { state: seed }
    }

    #[inline]
    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Uniform in [0, 1).
    #[inline]
    fn next_f64(&mut self) -> f64 {
        (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64
    }

    /// Standard normal via Box-Muller.
    #[inline]
    fn gauss(&mut self) -> f64 {
        let u1 = self.next_f64().max(1e-12);
        let u2 = self.next_f64();
        (-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos()
    }
}

/// Per-instrument simulation state.
#[derive(Debug, Clone)]
struct InstrumentSim {
    security_id: InstrumentId,
    mid: f64,
    rng: SplitMix64,
    rpt_seq: u32,
}

/// Generator configuration.
#[derive(Debug, Clone)]
pub struct GeneratorConfig {
    pub instruments: Vec<InstrumentId>,
    /// Long-run mean / starting mid (price units).
    pub base_price: f64,
    /// Minimum price increment.
    pub tick: f64,
    /// Half the bid/ask spread, in ticks.
    pub half_spread_ticks: i64,
    /// OU mean-reversion speed (0,1].
    pub theta: f64,
    /// OU shock scale (price units).
    pub sigma: f64,
    /// Quoted size at the touch.
    pub size: i32,
    /// PRNG seed (reproducibility).
    pub seed: u64,
}

impl Default for GeneratorConfig {
    fn default() -> GeneratorConfig {
        GeneratorConfig {
            instruments: vec![1],
            base_price: 5000.0,
            tick: 0.25,
            half_spread_ticks: 1,
            theta: 0.05,
            sigma: 0.5,
            size: 10,
            seed: 0xC0FF_EE12_3456_789A,
        }
    }
}

/// Synthetic MDP 3.0 packet generator.
pub struct Generator {
    sims: Vec<InstrumentSim>,
    cfg: GeneratorConfig,
    next_idx: usize,
    seq: u32,
    sending_time: u64,
}

impl Generator {
    /// Build a generator. Each instrument gets an independent PRNG stream
    /// derived from the base seed.
    pub fn new(cfg: GeneratorConfig) -> Generator {
        let sims = cfg
            .instruments
            .iter()
            .enumerate()
            .map(|(i, &security_id)| InstrumentSim {
                security_id,
                mid: cfg.base_price,
                rng: SplitMix64::new(cfg.seed ^ (i as u64).wrapping_mul(0x9E37_79B9_7F4A_7C15)),
                rpt_seq: 0,
            })
            .collect();
        Generator {
            sims,
            cfg,
            next_idx: 0,
            seq: 1,
            sending_time: 1,
        }
    }

    /// The instruments this generator emits, in registration order.
    pub fn instruments(&self) -> &[InstrumentId] {
        &self.cfg.instruments
    }

    /// Advance one instrument (round-robin) and return its next MDP 3.0 packet.
    pub fn next_packet(&mut self) -> Vec<u8> {
        let idx = self.next_idx;
        self.next_idx = (self.next_idx + 1) % self.sims.len();

        let tick = self.cfg.tick;
        let half = self.cfg.half_spread_ticks;
        let (theta, sigma, mu) = (self.cfg.theta, self.cfg.sigma, self.cfg.base_price);

        let (security_id, bid_px, offer_px, rpt_seq) = {
            let sim = &mut self.sims[idx];
            // Discrete Ornstein-Uhlenbeck step (AR(1) mean reversion).
            let z = sim.rng.gauss();
            sim.mid += theta * (mu - sim.mid) + sigma * z;
            sim.rpt_seq += 1;

            let mid_ticks = (sim.mid / tick).round() as i64;
            let bid = f64_to_price9((mid_ticks - half) as f64 * tick);
            let offer = f64_to_price9((mid_ticks + half) as f64 * tick);
            (sim.security_id, bid, offer, sim.rpt_seq)
        };

        let size = self.cfg.size;
        let make = |px_raw, entry_type| MdEntry {
            security_id,
            rpt_seq,
            px_raw,
            size,
            num_orders: 1,
            price_level: 1,
            update_action: MdUpdateAction::Overlay,
            entry_type,
        };
        let entries = [
            make(bid_px, MdEntryType::Bid),
            make(offer_px, MdEntryType::Offer),
        ];

        let seq = self.seq;
        let sending_time = self.sending_time;
        self.seq = self.seq.wrapping_add(1);
        self.sending_time += 1;

        let mut pb = PacketBuilder::new(seq, sending_time);
        pb.add_incremental_refresh(
            sending_time,
            crate::mdp3::enums::MatchEventIndicator::END_OF_EVENT,
            &entries,
        );
        pb.finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mdp3::book_refresh::IncrementalRefresh;
    use crate::mdp3::header::messages;
    use crate::mdp3::packet::PacketHeader;
    use crate::orderbook::{Bbo, OrderBook};

    fn cfg(instruments: Vec<InstrumentId>) -> GeneratorConfig {
        GeneratorConfig {
            instruments,
            ..GeneratorConfig::default()
        }
    }

    /// Decode a packet and apply it to a book, returning the last BBO produced.
    fn apply_packet(ob: &mut OrderBook, packet: &[u8]) -> Option<Bbo> {
        let (_, body) = PacketHeader::parse(packet)?;
        let mut last = None;
        for m in messages(body) {
            let r = IncrementalRefresh::decode(m.header, m.body)?;
            for e in r.entries() {
                last = ob.apply(&e);
            }
        }
        last
    }

    #[test]
    fn same_seed_produces_identical_bytes() {
        let mut a = Generator::new(cfg(vec![1, 2]));
        let mut b = Generator::new(cfg(vec![1, 2]));
        for _ in 0..50 {
            assert_eq!(a.next_packet(), b.next_packet());
        }
    }

    #[test]
    fn round_robins_instruments() {
        let mut g = Generator::new(cfg(vec![10, 20, 30]));
        let mut seen = Vec::new();
        for _ in 0..3 {
            let packet = g.next_packet();
            let (_, body) = PacketHeader::parse(&packet).unwrap();
            for m in messages(body) {
                let r = IncrementalRefresh::decode(m.header, m.body).unwrap();
                seen.push(r.entries().next().unwrap().security_id);
            }
        }
        assert_eq!(seen, vec![10, 20, 30]);
    }

    #[test]
    fn produced_packets_build_a_valid_bbo() {
        let mut g = Generator::new(cfg(vec![1]));
        let mut ob = OrderBook::with_instruments(&[1]);
        let mut got_bbo = None;
        for _ in 0..20 {
            let packet = g.next_packet();
            if let Some(bbo) = apply_packet(&mut ob, &packet) {
                got_bbo = Some(bbo);
            }
        }
        let bbo = got_bbo.expect("a BBO was produced");
        let bid = bbo.bid_px_raw.expect("bid present");
        let offer = bbo.offer_px_raw.expect("offer present");
        assert!(bid < offer, "bid {bid} must be below offer {offer}");
    }

    #[test]
    fn mid_mean_reverts_around_base_price() {
        let mut g = Generator::new(cfg(vec![1]));
        let mut ob = OrderBook::with_instruments(&[1]);
        let base = GeneratorConfig::default().base_price;
        let mut min_mid = f64::INFINITY;
        let mut max_mid = f64::NEG_INFINITY;
        for _ in 0..2000 {
            let packet = g.next_packet();
            if let Some(bbo) = apply_packet(&mut ob, &packet) {
                if let Some(mid) = bbo.mid() {
                    min_mid = min_mid.min(mid);
                    max_mid = max_mid.max(mid);
                }
            }
        }
        // A mean-reverting series oscillates on both sides of its mean.
        assert!(min_mid < base, "min mid {min_mid} should dip below {base}");
        assert!(max_mid > base, "max mid {max_mid} should rise above {base}");
        // And it must not diverge far from the mean.
        assert!((max_mid - base).abs() < base * 0.05);
    }
}
